export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";
export const GET_POSTS = "GET_POSTS";
export const POSTS_ERROR = "POSTS_ERROR";
export const DELETE_POST = "DELETE_POST";
export const ADD_AGENT = "ADD_AGENT";
export const AGENT_ERROR = "AGENT_ERROR";
export const GET_AGENT = "GET_AGENT";
export const GET_MUNICIPALITE = "GET_MUNICIPALITE";
export const GET_ADMIN = "GET_ADMIN";
export const DELETE_ADMIN = "DELETE_ADMIN";
export const ADMIN_ERROR = "ADMIN_ERROR";
export const MUNICIPALITE_ERROR = "MUNICIPALITE_ERROR";
export const CREATE_MUNICIPALITE = "CREATE_MUNICIPALITE";
export const DELETE_MUNICIPALITE = "DELETE_MUNICIPALITE";
export const GET_COUNT = "GET_COUNT";
export const DELETE_COUNT = "DELETE_COUNT";
export const COUNT_ERROR = "COUNT_ERROR";
export const LEAVE = "LEAVE";

export const GET_FILE_CREATION_DATE = "GET_FILE_CREATION_DATE";
export const GET_FILE_CREATION_DATE_ERROR = "GET_FILELOG_CREATION_DATE_ERROR";

export const GET_FILELOG_UPDATE_DATE = "GET_FILELOG_UPDATE_DATE";
export const GET_FILELOG_UPDATE_DATE_ERROR = "GET_FILELOG_UPDATE_DATE_ERROR";

export const GET_FILE = "GET_FILE";
export const GET_FILE_ERROR = "GET_FILE_ERROR";

export const GET_FILE_CONDITIONS = "GET_FILE_CONDITIONS";
export const GET_FILE_CONDITIONS_ERROR = "GET_FILE_CONDITIONS_ERROR";

export const GET_FILE_PIECES = "GET_FILE_PIECES";

export const GET_FILE_PIECES_ERROR = "GET_FILE_PIECES_ERROR";

export const SEND_FILE_ID_TO_COMPONENT = "SEND_FILE_ID_TO_COMPONENT";
export const SEND_FILE_ID_TO_COMPONENT_ERROR =
  "SEND_FILE_ID_TO_COMPONENT_ERROR";

export const GET_FILELOG_BY_FILE_ID = "GET_FILELOG_BY_FILE_ID";
export const GET_FILELOG_BY_FILE_ID_ERROR = "GET_FILELOG_BY_FILE_ID_ERROR";

export const GET_FILELOG_UPDATE_DATE_TODAY = "GET_FILELOG_UPDATE_DATE_TODAY";
export const GET_FILELOG_UPDATE_DATE_ERROR_TODAY =
  "GET_FILELOG_UPDATE_DATE_ERROR_TODAY";

export const GET_FILE_CREATION_DATE_TODAY = "GET_FILE_CREATION_DATE_TODAY";
export const GET_FILE_CREATION_DATE_ERROR_TODAY =
  "GET_FILELOG_CREATION_DATE_ERROR_TODAY";

export const SEND_FILE_ID_TO_COMPONENT_FILE = "SEND_FILE_ID_TO_COMPONENT_FILE";
export const SEND_FILE_ID_TO_COMPONENT_ERROR_FILE =
  "SEND_FILE_ID_TO_COMPONENT_ERROR_FILE";

export const GET_ONE_AGENT = "GET_ONE_AGENT";
export const ONE_AGENT_ERROR = "ONE_AGENT_ERROR";
